import React from "react";
import { ComponentStory, ComponentMeta } from "@storybook/react";

import Maze from "./maze";
import { CellType } from "./maze.type";

export default {
  title: "components/maze",
  component: Maze,
  argTypes: {},
} as ComponentMeta<typeof Maze>;

const Template: ComponentStory<typeof Maze> = (args) => <Maze {...args} />;

export const simple = Template.bind({});

simple.args = {
  size: 8,
  cells: [
    CellType.Empty,
    CellType.Empty,
    CellType.Empty,
    CellType.Empty,
    CellType.Empty,
    CellType.Empty,
    CellType.Empty,
    CellType.Empty,
    CellType.Empty,
    CellType.Wall,
    CellType.Wall,
    CellType.Wall,
    CellType.Wall,
    CellType.Wall,
    CellType.Empty,
    CellType.Empty,
    CellType.Empty,
    CellType.Empty,
    CellType.Empty,
    CellType.Empty,
    CellType.Rat,
    CellType.Wall,
    CellType.Empty,
    CellType.Wall,
    CellType.Empty,
    CellType.Empty,
    CellType.Empty,
    CellType.Empty,
    CellType.Empty,
    CellType.Wall,
    CellType.Empty,
    CellType.Wall,
    CellType.Wall,
    CellType.Wall,
    CellType.Wall,
    CellType.Wall,
    CellType.Empty,
    CellType.Empty,
    CellType.Empty,
    CellType.Wall,
    CellType.Empty,
    CellType.Cheese,
    CellType.Wall,
    CellType.Empty,
    CellType.Empty,
    CellType.Empty,
    CellType.Empty,
    CellType.Empty,
    CellType.Wall,
    CellType.Empty,
    CellType.Wall,
    CellType.Empty,
    CellType.Wall,
    CellType.Wall,
    CellType.Wall,
    CellType.Empty,
    CellType.Wall,
    CellType.Empty,
    CellType.Empty,
    CellType.Empty,
    CellType.Empty,
    CellType.Empty,
    CellType.Empty,
    CellType.Empty,
  ],
};
